import Head from 'next/head'
import { BiPlus } from 'react-icons/bi';
import Link from 'next/link';

export default function Home() {
  return (
    <section>
      <Head>
        <title>InfoinKelas - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='py-5'>
        {/* navbar */}
        <nav>
          <div className='flex items-center justify-center border-b-2'>
            <ul className='flex flex-col p-4 mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium'>
              <li>
                <a href="" className='aria-current="page"'>Home</a>
              </li>
              <li>
                <a href="#" className="">About</a>
              </li>
              <li>
                <a href="#" className="">Login</a>
              </li>
            </ul>
          </div>
        </nav>
        <div className='mainPage py-5'>
          <div className='join'>
            {/* <h2>Join now</h2> */}
          </div>
        </div>
      </main>

    </section>
  )
}

{/* <h1 className='text-center'>
  <a href="crud">CRUD</a>
</h1> */}